name:base
channels:
- conda-forge
- bioconda
- defauts
dependencies:
  - python=3.9
  - r-base=4.0
  - r-dplyr
  - r-tidyverse
  - r-ggplot2
  - r-reshape2
  -pip
  -pip:
     - numpy
     - pandas
     - matplotlib
     - scikit-learn
     
